name: Firmware Downloader Ultra

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # 赋予创建 Release 的权限
      contents: write
    steps:
      - name: Download Firmware
        run: |
          # 加上 -c 支持断点，-t 重试
          wget -c -t 10 "https://oxygenos.oneplus.com/CPH2747_11_C_OTA_0300-1010_patch_o2ZAY3_01000100.zip" -O firmware.zip

      - name: Calculate MD5 (可选校验)
        run: md5sum firmware.zip

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: OnePlus Firmware Download
          files: firmware.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
